version: '3.8'
services:
  app:
    build:
      context: demo/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/kokodi
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345678
      - SPRING_REDIS_HOST=redis
    networks:
      - kokodi-network

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=kokodi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kokodi-network

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - kokodi-network

networks:
  kokodi-network:
    driver: bridge

volumes:
  postgres-data:
